dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "sonarcloud"
    token:
      secure: dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "sonarcloud"
    token:
      secure: $SONAR_TOKEN1

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
